### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [brettkromkamp/typed-tree#1]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.0.3. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary typed-tree -w /tmp/ext typed-tree==1.0.3
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting typed-tree==1.0.3
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/e9f/0e549ebd95d11/typed-tree-1.0.3.tar.gz (4.8 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-a2q1l1eq/typed-tree/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-a2q1l1eq/typed-tree/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-a2q1l1eq/typed-tree/pip-egg-info
         cwd: /tmp/pip-wheel-a2q1l1eq/typed-tree/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-a2q1l1eq/typed-tree/setup.py", line 16, in <module>
        with open(os.path.join(here, 'HISTORY.rst'), encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-a2q1l1eq/typed-tree/HISTORY.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by brettkromkamp** [comment]
@thatch Thanks for reporting the issue. I’ll look into the issue later today. Seems like it is complaining about a missing HISTORY.rst file?

I wonder if the HISTORY.rst file being an empty file is the cause of the issue. Or, actually related to the MANIFEST.in file. Anyway, I’ll take a look.
